[package]
name = "fractal"
version = "0.1.0"
description = "Generate various fractals in rust"
authors = ["Luke"]
license = "MIT"
edition = "2021"

[dependencies]
num = "0.4"
image = "0.24.6"
imageproc = "0.23.0"
rayon = "1.7"
