[package]
name = "fractal"
version = "0.1.0"
description = "Generate various fractals in rust"
authors = ["Luke"]
license = "MIT"
edition = "2021"

[dependencies]
image = "0.24.6"
colorgrad = "0.6.2"
rayon = "1.7"
